#!/usr/bin/env python3
"""datac.py <textid.inc> <party.txt> <enemies.txt> <party.inc>

Compiles the party and enemy data into party.inc (constants and the layout
of one party member and one enemy type; included at the top) and
partytab.inc next to it (start values, rank table, enemy types; included
with the data at the end).

One party member (all words):
  p_name p_role (text ids), p_rank (0..), p_xp, p_hp, p_hpmax (current
  maximum, lowered by a Deep Wound), p_hpbase (real maximum), p_atk, p_def,
  p_spd, p_find, p_bleed (0 none, 1 Scratch, 2 Gash, 3 Deep Wound),
  p_flags (later: poison, stun, fear), p_fen, p_dry, p_glow (moss),
  p_mosscap (moss of all kinds together)

One enemy type (all words): e_name e_plural (text ids), e_hp, e_atk, e_def,
  e_spd, e_bleed, e_xp. The types are numbered in file order (ET_<id>).
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import enemies  # noqa: E402

EFIELDS = ['name', 'plural', 'hp', 'atk', 'def', 'spd', 'bleed', 'xp']
FIELDS = ['name', 'role', 'rank', 'xp', 'hp', 'hpmax', 'hpbase', 'atk', 'def',
          'spd', 'find', 'bleed', 'flags', 'fen', 'dry', 'glow', 'mosscap']
NPARTY = 4


def fail(msg):
    sys.exit('datac: ' + msg)


def main():
    if len(sys.argv) != 5:
        fail(__doc__.splitlines()[0])
    ids = {}
    for line in open(sys.argv[1]):
        m = re.match(r'^T_(\w+)\s+equ\s+(\d+)', line)
        if m:
            ids[m.group(1)] = int(m.group(2))
    src = sys.argv[2]

    def text(where, name):
        if name not in ids:
            fail('%s: unknown text id %s' % (where, name))
        return ids[name]

    cats, ranks, consts = [], [], {}
    for n, raw in enumerate(open(src, encoding='ascii').read().splitlines(), 1):
        where = '%s:%d' % (src, n)
        line = raw.split('#', 1)[0].split()
        if not line:
            continue
        key, args = line[0], line[1:]
        try:
            if key in ('bleedsteps', 'deepmin') and len(args) == 1:
                consts[key] = int(args[0])
            elif key == 'rank' and len(args) == 2:
                ranks.append((text(where, args[0]), int(args[1])))
            elif key == 'cat' and len(args) == 11:
                name, role = text(where, args[0]), text(where, args[1])
                hp, atk, df, spd, find, cap, fen, dry, glow = map(int, args[2:])
                if fen + dry + glow > cap:
                    fail('%s: more moss than the cat can carry' % where)
                cats.append(dict(name=name, role=role, rank=0, xp=0, hp=hp, hpmax=hp,
                                 hpbase=hp, atk=atk, def_=df, spd=spd, find=find,
                                 bleed=0, flags=0, fen=fen, dry=dry, glow=glow,
                                 mosscap=cap))
            else:
                fail('%s: cannot read "%s"' % (where, raw.strip()))
        except ValueError:
            fail('%s: number expected' % where)
    if len(cats) != NPARTY:
        fail('%s: %d cats needed' % (src, NPARTY))
    if not ranks or ranks[0][1] != 0 or any(a[1] >= b[1] for a, b in zip(ranks, ranks[1:])):
        fail('%s: ranks must start at 0 XP and rise' % src)
    for k in ('bleedsteps', 'deepmin'):
        if k not in consts:
            fail('%s: missing "%s"' % (src, k))

    foes = enemies.read(sys.argv[3])
    for e in foes:
        e['name'] = text(e['where'], e['name'])
        e['plural'] = text(e['where'], e['plural'])
    inc = sys.argv[4]
    with open(inc, 'w') as f:
        f.write('; GENERATED by tools/datac.py from data/party.txt - do not edit\n')
        f.write('NPARTY      equ %d\n' % NPARTY)
        f.write('NRANKS      equ %d\n' % len(ranks))
        f.write('BLEED_STEPS equ %d  ; steps per bleeding tick\n' % consts['bleedsteps'])
        f.write('DEEP_MIN    equ %d  ; percent of max HP a Deep Wound leaves\n'
                % consts['deepmin'])
        for i, fld in enumerate(FIELDS):
            f.write('p_%-8s equ %d\n' % (fld, 2 * i))
        f.write('p_size     equ %d\n' % (2 * len(FIELDS)))
        f.write('NENEMY      equ %d\n' % len(foes))
        for i, e in enumerate(foes):
            f.write('ET_%-16s equ %d\n' % (e['id'], i))
        for i, fld in enumerate(EFIELDS):
            f.write('e_%-8s equ %d\n' % (fld, 2 * i))
        f.write('e_size     equ %d\n' % (2 * len(EFIELDS)))
    with open(os.path.join(os.path.dirname(inc), 'partytab.inc'), 'w') as f:
        f.write('; GENERATED by tools/datac.py from data/party.txt - do not edit\n')
        f.write('partyinit:\n')
        for c in cats:
            vals = [c['def_' if fld == 'def' else fld] for fld in FIELDS]
            f.write('        dc.w    %s\n' % ','.join(map(str, vals)))
        f.write('rankxp:   dc.w    %s\n' % ','.join(str(x) for _, x in ranks))
        f.write('rankname: dc.w    %s\n' % ','.join(str(t) for t, _ in ranks))
        f.write('enemytab:\n')
        for e in foes:
            f.write('        dc.w    %s  ; %s\n'
                    % (','.join(str(e[k]) for k in EFIELDS), e['id']))
    print('datac: %d cats, %d ranks, %d enemy types' % (len(cats), len(ranks), len(foes)))


if __name__ == '__main__':
    main()
